server: 
  port: 9527
 
spring: 
  profiles: dev
  application:
    name: springcloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
zuul:
  ignored-services: service-provider
  prefix: /yaorange  
  routes: 
    mydept.serviceId: service-provider
    mydept.path: /mydept/** 
info: 
  app.name: yaorange-microservicecloud
  company.name: www.qiangge.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$    

